apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: hello-kiamol
  labels:
    kiamol: ch15
  annotations:
    kubernetes.io/ingress.class: "nginx" 
spec:
  rules:
  - host: hello.kiamol.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service.name: hello-kiamol
          service.port.number: 80