apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: todo
  labels:
    kiamol: ch15
spec:
  rules:
  - host: todo.kiamol.local
    http:
      paths:
      - path: /
        pathType: Exact   
        backend:
          service:
            name: todo-web
            port:
              number: 80
      - path: /list
        pathType: Exact
        backend:
          service:
            name: todo-web
            port:
              number: 80
      - path: /new
        pathType: Exact
        backend:
          service:
            name: todo-web
            port:
              number: 80
      - path: /static
        pathType: Prefix
        backend:
          service:
            name: todo-web
            port:
              number: 80